In [1]:
import cv2
import numpy as np

image = cv2.imread("fruits.jpg")
cv2.imshow("image", image)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [10]:
hsv = cv2.cvtColor(image, cv2.COLOR_BGR2HSV)
cv2.imshow("hsv", hsv)
cv2.waitKey(0)
cv2.destroyAllWindows()
# The reason why the image looks so weird when shown as an image is because the-
# hue value is not in the proper range, så instead of white, it will show red. 

In [11]:
h, s, v = cv2.split(hsv)

cv2.imshow("Hue", h)  # Viser farvetone
cv2.imshow("Saturation", s)  # Viser mætning
cv2.imshow("Value", v)  # Viser lysstyrke

cv2.waitKey(0)
cv2.destroyAllWindows()


In [12]:
print(f"Here is hue {h}")
print(f"Here is saturation {s}")
print(f"Here is value {v}")

Here is hue [[100 100 100 ... 100 100 100]
 [100 100 100 ... 100 100 100]
 [100 100 100 ... 100 100 100]
 ...
 [100 100 100 ... 100 100 100]
 [100 100 100 ... 100 100 100]
 [100 100 100 ... 100 100 100]]
Here is saturation [[78 78 78 ... 76 76 76]
 [78 78 78 ... 76 76 76]
 [78 78 78 ... 76 76 76]
 ...
 [89 89 89 ... 82 82 82]
 [89 89 89 ... 82 82 82]
 [89 89 89 ... 82 82 82]]
Here is value [[229 229 229 ... 236 236 236]
 [229 229 229 ... 236 236 236]
 [229 229 229 ... 236 236 236]
 ...
 [224 224 224 ... 222 222 222]
 [224 224 224 ... 222 222 222]
 [224 224 224 ... 222 222 222]]


In [13]:
# Opret en farvevisualisering af Hue-kanalen
hue_colored = cv2.merge([h, np.full_like(h, 255), np.full_like(h, 255)])
hue_colored = cv2.cvtColor(hue_colored, cv2.COLOR_HSV2BGR)

cv2.imshow("Hue (colored)", hue_colored)
cv2.imshow("Saturation (grayscale)", s)
cv2.imshow("Value (grayscale)", v)

cv2.waitKey(0)
cv2.destroyAllWindows()


In [14]:
# Gem billedet som en HSV-fil
cv2.imwrite("fruits_hsv.jpg", hsv)

True